[package]
name = "back-end"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15"
rocket = "0.5.1"
postgres = { version = "0.19.7", features = ["with-chrono-0_4", "with-uuid-1"] }
rust_decimal = "1.14.0"
chrono = "0.4"
rand = "0.8.5"
uuid = "1.8.0"
